### ISSUE TITLE
How to disable rewrite?

### ISSUE THREAD

**Issue by DrLynix** [ivandiazwm/phpback#139] opened 2017-11-13 23:23 UTC
Hi,

I just set up phpback on my server (with PHP 7) and it does works well. Until i try to login.

I'm using nginx as a web server and it doesn't handle .htaccess files which enable rewrite rules.

Is it possible to not use URL rewrite with phpback?

Thanks

**Comment by DanielRuf** [comment] 2018-02-06 05:59
Probably no. There are modules and instructions on the internet how you van use the rewrite rules and .htaccess with nginx.

**Comment by murmelbahn** [comment] 2018-05-11 11:02
Can someone help me with the rewrite rules for nginx?

**Comment by DanielRuf** [comment] 2018-05-11 11:07
You can use either a module which adds support for .htaccess in Nginx or you may have to port the rules manually.

Sorry, never did the porting stuff in bigger projects.

**Comment by murmelbahn** [comment] 2018-05-11 11:11
Okay, then i have to port them. Which of all the htaccess files is responsible for the error mentioned by DrLynix?

**Comment by murmelbahn** [comment] 2018-05-11 11:28
Oh, i've figgured out by myself.
I've created a new location in my config file under /etc/nginx/sites-enabled

location /$path/to/phpback {
if (!-e $request_filename){ rewrite ^(.*)$ /$path/to/phpback/index.php?/$args; }
    }

It seems like everything is working now.

**Comment by DanielRuf** [comment] 2018-05-11 11:31
Awesome =)

**Comment by DanielRuf** [comment] 2019-03-03 14:42
Closing as I think the issue is resolved.

**Closed by DanielRuf** 2019-03-03 14:42 UTC
