### ISSUE TITLE
Too long title pushes other items out of the browser screen

### ISSUE THREAD

**Issue by mzch** [ivandiazwm/phpback#167] opened 2019-05-26 14:48 UTC
Hi,

When creating an idea with too long title (e.g. near 100 chars), it pushes other items (date, categories, etc) out of the admin screen. Please fix this issue.

And one thing, such a long title breaks layouts itself. This issue will need to be fixed.

**Comment by drveresh** [comment] 2021-04-19 18:30
@DanielRuf, if the issue still persists, then can you please share the screenshot? I just tested it and couldn't reproduce it.

**Comment by DanielRuf** [comment] 2021-04-19 18:49
@drveresh sorry, but I guess you misinterpreted something. I've just added the `bug` label as collaborator. I am not the creator of this issue, so I have no further details about this problem.

**Comment by DanielRuf** [comment] 2021-04-19 18:51
Closing as there are no additional details.

**Closed by DanielRuf** 2021-04-19 18:51 UTC
Labels: bug
